#!/bin/sh
# To use add to `.git/hooks/`
# Should be named `pre-push`
# Make executable with `chmod +x`
# Or git config core.hooksPath .githooks

# stash any unstaged changes
git stash -q --keep-index

flutter pub run build_runner build --delete-conflicting-outputs

flutter analyze

flutter test

# if wrong, recover the stashed changes
if [ $? -ne 0 ]; then
        git stash pop -q
        exit 1
fi

# unstash the unstashed changes
git stash pop -q
exit 0